### ISSUE TITLE
Power loss on Relog

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Darkhax-Minecraft/SolarVillage#1]
The power in the solar panels get lost when a user relogs form the world  [Example GIF](http://ss.unrealdinnerbone.x10.bz/2016-06-19_10-54-05.gif)

**Comment by Darkhax** [comment]
This issue was closed with https://github.com/Darkhax-Minecraft/SolarVillage/commit/a227905a9272483f7278b0b2f87b9ea3e5ed3578 but I forgot to close. The panel is not losing power in your test, the power is just not syncing to the client side after relog.
